spring:
  application:
    name: identify-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mealgo_identity}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:PhongTM@2002}
    driver-class-name: org.postgresql.Driver
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT:8082}

app:
  jwt:
    issuer: ${JWT_ISSUER:http://localhost:${server.port}}
    audience: ${JWT_AUDIENCE:mealgo-api}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:15m}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:30d}
    private-key: ${JWT_PRIVATE_KEY:}
    public-key: ${JWT_PUBLIC_KEY:}
