spring:
  application:
    name: restaurant-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mealgo_restaurant
    username: postgres
    password: PhongTM@2002
    driver-class-name: org.postgresql.Driver
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
  packages-to-scan: com.mealgo.restaurant_service.controller

app:
  api:
    version: ${API_VERSION:1.0.0}

server:
  port: 8081
