spring:
  application:
    name: restaurant-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mealgo_restaurant
    username: postgres
    password: PhongTM@2002
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: create

    show-sql: false

    properties:
      hibernate:
        format_sql: false

apikit:
  problem:
    type-base-uri: https://apikit.io/problems

server:
  port: 8081
